import { LazyModuleLoader } from '@nestjs/core';
import { ArmamentosEmprestimos } from 'src/armamentos-emprestimos/armamento-emprestimo.interface';
import { ArmamentosEmprestimosService } from 'src/armamentos-emprestimos/armamentos-emprestimos.service';
import { Armamentos } from 'src/armamentos/armamento.interface';
import { ArmamentosService } from 'src/armamentos/armamentos.service';
import { Contratos } from 'src/contratos/contrato.interface';
import { ContratosService } from 'src/contratos/contratos.service';
import { GraduacoesService } from 'src/graduacoes/graduacoes.service';
import { MateriaisConsumoService } from 'src/materiais-consumo/materiais-consumo.service';
import { MateriaisConsumo } from 'src/materiais-consumo/material-consumo.interface';
import { MateriaisPoliciaisService } from 'src/materiais-policiais/materiais-policiais.service';
import { MateriaisPoliciais } from 'src/materiais-policiais/material-policial.interface';
import { MateriaisService } from 'src/materiais/materiais.service';
import { Materiais } from 'src/materiais/material.interface';
import { PoliciaisAtestadosService } from 'src/policiais-atestados/policiais-atestados.service';
import { PoliciaisFeriasService } from 'src/policiais-ferias/policiais-ferias.service';
import { PoliciaisRequeridasService } from 'src/policiais-requeridas/policiais-requeridas.service';
import { PoliciaisService } from 'src/policiais/policiais.service';
import { SetoresService } from 'src/setores/setores.service';
import { User } from 'src/users/user.interface';
import { VeiculosOficinas } from 'src/veiculos-oficinas/veiculo-oficina.interface';
import { VeiculosOficinasService } from 'src/veiculos-oficinas/veiculos-oficinas.service';
import { VeiculosPoliciais } from 'src/veiculos-policiais/veiculo-policial.interface';
import { VeiculosPoliciaisService } from 'src/veiculos-policiais/veiculos-policiais.service';
import { Veiculos } from 'src/veiculos/veiculo.interface';
import { VeiculosService } from 'src/veiculos/veiculos.service';
export declare class HomeService {
    private lazyModuleLoader;
    private armamentosService;
    private armamentosEmprestimosService;
    private contratosService;
    private graduacoesService;
    private materiaisService;
    private materiaisConsumoService;
    private materiaisPoliciaisService;
    private policiaisService;
    private policiaisAtestadosService;
    private policiaisFeriasService;
    private policiaisRequeridas;
    private veiculosService;
    private veiculosOficinasService;
    private veiculosPoliciaisService;
    private setoresService;
    constructor(lazyModuleLoader: LazyModuleLoader, armamentosService: ArmamentosService, armamentosEmprestimosService: ArmamentosEmprestimosService, contratosService: ContratosService, graduacoesService: GraduacoesService, materiaisService: MateriaisService, materiaisConsumoService: MateriaisConsumoService, materiaisPoliciaisService: MateriaisPoliciaisService, policiaisService: PoliciaisService, policiaisAtestadosService: PoliciaisAtestadosService, policiaisFeriasService: PoliciaisFeriasService, policiaisRequeridas: PoliciaisRequeridasService, veiculosService: VeiculosService, veiculosOficinasService: VeiculosOficinasService, veiculosPoliciaisService: VeiculosPoliciaisService, setoresService: SetoresService);
    armamentosEmprestados(params: any, idUser: User): Promise<ArmamentosEmprestimos>;
    armamentosVencendo(params: any, idUser: User): Promise<Armamentos>;
    atestados(params: any, idUser: User): Promise<number>;
    contratosAcabando(params: any, idUser: User): Promise<Contratos>;
    ferias(params: any, idUser: User): Promise<number>;
    materiaisConsumoVencendo(params: any, idUser: User): Promise<MateriaisConsumo>;
    materiaisAlerta(params: any, idUser: User): Promise<MateriaisConsumo>;
    materiaisEmprestados(params: any, idUser: User): Promise<MateriaisPoliciais>;
    materiaisVencendo(params: any, idUser: User): Promise<Materiais>;
    policiais(params: any, idUser: User): Promise<number>;
    policiaisGraduacoes(params: any, idUser: User): Promise<any>;
    policiaisSetores(params: any, idUser: User): Promise<any>;
    requeridas(params: any, idUser: User): Promise<any>;
    veiculosManutencao(params: any, idUser: User): Promise<VeiculosOficinas>;
    veiculosTrocaOleo(params: any, idUser: User): Promise<Veiculos>;
    veiculosRevisao(params: any, idUser: User): Promise<Veiculos>;
    veiculosEmprestados(params: any, idUser: User): Promise<VeiculosPoliciais>;
}
